### ISSUE TITLE
Duplicants Jobs tab crashes the editor.

### ISSUE THREAD

**Issue by JuanDaniel2510** [RoboPhred/oni-duplicity#9]
When I click on the jobs tab in any duplicant the editor goes blank. (It displays a empty page) The only thing I can do is reload the page a re-upload the save game.

I have tried with a new game  ( [save.zip](https://github.com/RoboPhred/oni-duplicity/files/2109362/save.zip) ) and it also crashes.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7580835/41511802-3baba0fa-7276-11e8-8fdc-4aef2d759f7e.gif)

(edit!) Game Info: Cosmic Update / Development Build: CU-273742

(edit2):
<img width="706" alt="error" src="https://user-images.githubusercontent.com/7580835/41512688-ab820af4-7285-11e8-832a-3c1f5f98974c.PNG">

**Comment by RoboPhred** [comment]
Thanks for the report!  This should be fixed.

Was caused by a difference in the way the new parser handles dictionary types.  The old parser used es6 maps, but the new one uses arrays to guarantee the ordering so that as little as possible changes when the file is saved again.

**Comment by JuanDaniel2510** [comment]
It's still happening to me. 
The same "t.toLowerCase is not a function" error.

**Comment by RoboPhred** [comment]
There was an issue with the deploy step and the site didn't get updated.  It should be fixed now, and I can confirm the site had updated correctly.  Can you check again?

The built in change log should say the most recent version is 1.4.2.  1.4.1 is the broken version.  It it still shows that, try clearing your cache.

**Comment by JuanDaniel2510** [comment]
It works!
Thanks you! 👍

**Comment by JuanDaniel2510** [comment]
And... I Spoke too soon:

<img width="1320" alt="oniseerror" src="https://user-images.githubusercontent.com/7580835/41539311-617e16ca-7305-11e8-8f6f-baef792c3362.png">

At least the Aptitudes tab works.

**Comment by RoboPhred** [comment]
Whoops, looks like I was a bit too overzealous in adding array indexers when handling the Map to array-of-pairs conversion.

Published fix, version should read 1.4.3

**Comment by JuanDaniel2510** [comment]
It still says 1.4.2 :P 

![imagen](https://user-images.githubusercontent.com/7580835/41569646-914ef654-7363-11e8-935d-93eb1008a044.png)

**Comment by RoboPhred** [comment]
I had to do a double take there.  The website is indeed running v1.4.3 with the included fix, but I added the changelog entry after building it, not before.  The changelog on the site is wrong, but everything else is working.
